server:
  port: 8888
#logging:
#  level:
#    root: debug
distribute:
  lock:
    redis:
      enable: true
      timeout: 1000
      retryCount: 1
      retryInterval: 1000
      password:
      nodes:
        - "redis://192.168.99.100:6379"
      type: single # 可选single，sentinel，master-slave